name: Deploy Azure Functions

on:
  push:
    branches: [ main ]

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Debug ZIP Contents
      run: |
        ls -la
        zip -r functionapp.zip .
        ls -la functionapp.zip

    - name: Deploy to Azure Functions
      uses: Azure/functions-action@v1
      with:
        app-name: 'function-midsem'
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
        enable-oryx-build: true
        remote-build: true

    - name: Test API
      run: |
        sleep 30
        curl -X POST "https://function-midsem-hkfhewhzagh6gucd.canadacentral-01.azurewebsites.net/api/items" \
          -H "Content-Type: application/json" \
          -d '{"name": "GitHub 401 FIXED!"}'
